apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/nv-device-plugin
  - ../base/metrics-server
  - ../base/postgres-operator
  - cilium
  - cert-manager
  - traefik
  - tailscale
  - nfs-provisioner
  - smtp
