apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/transmute
  - ingress.yaml
  - pvc.yaml
  - transmute-secrets.sops.yaml

patches:
  - path: transmute-patch.yaml
