apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmute-data
  namespace: transmute
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi   # CHANGE this to the amount of storage you want to allocate to transmute
