---
apiVersion: v1
kind: Service
metadata:
  name: proxysql
  namespace: proxysql
  labels:
    app.kubernetes.io/name: proxysql
spec:
  type: ClusterIP
  ports:
    - name: mysql-traffic
      port: 3306
      targetPort: 6033
      protocol: TCP
    - name: proxysql-admin
      port: 6032
      targetPort: 6032
      protocol: TCP
  selector:
    app.kubernetes.io/name: proxysql
