apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: models
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      # customise the tolerations and gpu node selector in the overlay

      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: ollama
          image: ollama/ollama:0.20.2
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: true
          env:
            - name: OLLAMA_MODELS
              value: /models
            - name: HOME
              value: "/models"
          ports:
            - containerPort: 11434
          volumeMounts:
            - name: ollama-data
              mountPath: /models
          resources:
            limits:
              nvidia.com/gpu: 1
      volumes:
        - name: ollama-data
          persistentVolumeClaim:
            claimName: ollama-models
