apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models
  namespace: models
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
