apiVersion: v1
kind: Secret
metadata:
    name: searxng-secrets
    namespace: searxng
type: Opaque
stringData:
    SEARXNG_SECRET: changeme             # Use `openssl rand -hex 32` to generate a random string
    SEARXNG_VALKEY_URL: valkey://:changeme@valkey.valkey.svc.cluster.local:6379/DB_NUMBER
