apiVersion: v1
kind: Secret
metadata:
    name: outline-secrets
    namespace: outline
type: Opaque
stringData:
    # General app configs
    URL: https://outline.example.com               # CHANGE this to your outline URL
    SECRET_KEY: "CHANGEME"                         # Use `openssl rand -hex 32` to generate a random string
    UTILS_SECRET: "CHANGEME"                       # Use `openssl rand -hex 32` to generate a random string

    # Configure this if you have deployed the postgres DB cluster
    PGHOST: pg-shared-rw.databases.svc.cluster.local
    PGPORT: "5432"
    PGDATABASE: outline
    PGUSER: outline
    PGPASSWORD: "CHANGEME"
    PGSSLMODE: allow

    # Configure this if you have an S3 compliant storage server set up
    FILE_STORAGE: s3
    FILE_STORAGE_UPLOAD_MAX_SIZE: "26214400"
    AWS_REGION: us-east-2
    AWS_S3_FORCE_PATH_STYLE: "true"                  # Set this to true for s3://bucket_url/outline/ style endpoints
    AWS_S3_ENDPOINT: S3_ENDPOINT                     # CHANGE this to primary endpoint of your s3 bucket
    AWS_S3_UPLOAD_BUCKET_NAME: "outline"             # CHANGE this to the name of your outline bucket
    AWS_S3_UPLOAD_BUCKET_URL: S3_PUBLIC_ENDPOINT     # CHANGE this to you public s3 endpoint, https required
    AWS_ACCESS_KEY_ID: "CHANGEME"                    # CHANGE this to your client_id
    AWS_SECRET_ACCESS_KEY: "CHANGEME"                # CHANGE this to your client_secret

    # Configure this if you have deployed the valkey cluster
    REDIS_HOST: valkey.valkey.svc.cluster.local
    REDIS_PORT: "6379"
    REDIS_USERNAME: ""
    REDIS_PASSWORD: CHANGEME                        # CHANGE this to the valkey cluster password
    REDIS_URL: redis://USER:PASSWORD@valkey.valkey.svc.cluster.local:6379/DB_NUMBER  # Set these values accordingly

    # Configure this is you have deployed the smtp-relay
    SMTP_HOST: smtp-relay.smtp.svc.cluster.local
    SMTP_PORT: "25"
    SMTP_USERNAME: ""
    SMTP_PASSWORD: ""
    SMTP_FROM_EMAIL: outline@example.com
    SMTP_REPLY_EMAIL: no-reply@example.com
    SMTP_SECURE: "false"
