apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ghost-values.sops.yaml
  - ../../base/ghostcms

patches:
  - path: helmrelease-patch.yaml
    target:
      kind: HelmRelease
      name: ghostcms
