apiVersion: v1
kind: Secret
metadata:
    name: authelia-user-secrets
    namespace: authelia
type: Opaque
stringData:
    # see https://www.authelia.com/reference/guides/passwords/ for more info
    # use `docker run --rm -it authelia/authelia:latest authelia crypto hash generate argon2` to generate
    # remove comments before using
    users.yml: |
        users:
          joe_bloggs:                          # username to login with
            password: "changeme"               # password to login with
            displayname: "Joe Bloggs"          # user display name
            email: "joe.bloggs@example.com"    # user email address
            groups:                            # groups allocated to the user
              - admins
              - users
              - dev
