apiVersion: v1
kind: Secret
metadata:
    name: oidc-secrets
    namespace: authelia
type: Opaque
stringData:
    # Application OIDC secrets - generate with `just authelia-hash`
    oidc.client.linkding.value: changeme
    oidc.client.forgejo.value: changeme
    oidc.client.directus.value: changeme
    oidc.client.paperless.value: changeme
    oidc.client.lubelogger.value: changeme
    oidc.client.outline.value: changeme
    oidc.client.transmute.value: changeme
    oidc.client.n8n.value: changeme
    oidc.client.openwebui.value: changeme
    oidc.client.harbor.value: changeme

    # Authelia rsa private key - generate with `openssl genrsa -out private.pem 4096`
    oidc.jwk.rsa256.pem: |-
        -----BEGIN PRIVATE KEY-----
        YOUR_KEY_HERE - GENERATE WITH
        -----END PRIVATE KEY-----
