apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# ---
# Placeholder for the HomeOps Blueprint
# Add your application manifests or overlays to the resources list below
# ---

resources: []
