apiVersion: v1
kind: Secret
metadata:
    name: pg-example-creds
    namespace: databases
type: Opaque
stringData:
    username: changeme         # database username
    password: changeme         # database password
