apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backups.yaml
  - barman-objstore.yaml
  - cluster-databases.yaml
  - creds-example.sops.yaml
  - custom-queries.yaml
  - db-cluster.yaml
  - namespace.yaml
  - pooler.yaml
