apiVersion: v1
kind: Secret
metadata:
    name: valkey-auth-secret
    namespace: valkey
type: Opaque
stringData:
    valkey-password: ENC[AES256_GCM,data:vYOL+Tvzq0EnTjIvuizbdzNtGOxF8dkIU9Np/Vu0f2SOtw==,iv:epYx680GblVixF1FGqKyR3NGxEW4TfpN/BIz4V4C394=,tag:T5wSVnwNfKrviW2yXb9+eg==,type:str]
sops:
    age:
        - recipient: age1gakv6vtdd4x5z37evaq50930m89envq5xqd0m8sgwtudxx0gjalqvz7rze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2c3l0Tm9iSHdIczVESUpl
            Ym4rcG9BMTl3eVhyaFN2TjRmdFJGcEVNeHhRCk5VU2txbWRGRTlrNjBPdiswZWtZ
            WkhPOEw2RnJSZUUwNzBySnA4Zk9lR3MKLS0tIDNEejJjaE00cW1JYmVhR3doMUxO
            N2NWMkdvU0NxbndIckhqVlFNVkVNL1kKnVFB5SASTt84ddyuCgDmErvhmj9dZwvu
            HlGnDVsFqD4Jbt3S7EVP1gtNKRsU+9JbTrDCH7g1NFxq4kuLjIaw4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T07:44:41Z"
    mac: ENC[AES256_GCM,data:KQnWrDO0QI6WOZ18RmNCf1Rvgtm9eW882FaMWZ5gs5VMS53DMpJPepZSM7H/ubOmENBkV8STPvOvRpKUUJRLWYwGdAbQFqNdYvXPzerofO9FgAFXfeqtlbFKh5x67kwtXT2AmTL3qquJ6nwRP04sY/IFtxfMymxerphXZy9QDWM=,iv:DwfK2pqxni2hTuomtpw76sHA2pqheK6OhP0l+RaOgw8=,tag:KtNnpm0dWdV8OgMOIZDx1g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
