apiVersion: v1
kind: Secret
metadata:
    name: valkey-auth-secret
    namespace: valkey
type: Opaque
stringData:
    valkey-password: CHANGEME      # CHANGE this to the password of your redis cluster
