apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/podinfo

patches:
  # apply this patch if you want an ingress for your podinfo instance
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: YOUR_PODINFO_HOSTNAME
      - op: replace
        path: /spec/tls/0/hosts/0
        value: YOUR_PODINFO_HOSTNAME
    target:
      kind: Ingress
      name: podinfo-ingress
