apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/uptime-kuma
  - ingressroute.yaml
  - uptime-kuma-tls.yaml
#  - uptime-kuma-secrets.sops.yaml   # Add this is you configure MySQL/MariaDB for Uptime Kuma

patches:
  - path: pvc-patch.yaml
  - path: uptime-kuma-patch.yaml
