apiVersion: v1
kind: Secret
metadata:
    name: uptime-kuma-secrets
    namespace: uptime-kuma
type: Opaque
stringData:
    # Configure this if you have a mysql/mariadb cluster set up
    UPTIME_KUMA_DB_TYPE: mariadb
    UPTIME_KUMA_DB_HOSTNAME: MYSQL_HOSTNAME
    UPTIME_KUMA_DB_PORT: "3306"
    UPTIME_KUMA_DB_USERNAME: MYSQL_USERNAME
    UPTIME_KUMA_DB_PASSWORD: MYSQL_PASSWORD
    UPTIME_KUMA_DB_NAME: MYSQL_DATABASE_NAME
