apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/tailscale
  - audiobookshelf
  - directus
  - drawio
  - forgejo
  - ghostcms
  - homepage
  - linkding
  - lubelogger
  - navidrome
  - n8n
  - ollama
  - openwebui
  - outline
  - podinfo
  - transmute
  - uptime-kuma
