apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/tailscale
  - podinfo
  - homepage
  - directus
  - draw.io
  - linkding
  - outline
  - transmute
  - uptime-kuma
