# smtp-relay-secrets.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: smtp-relay
    namespace: smtp
stringData:
    smtp-relay-password: ENC[AES256_GCM,data:DF1L1+N6s18aO0H0dfgQX4y+zFgS/Hrn0qiRlIjtn9aejygmm2oz6ClPOlT5EegPdP4=,iv:2l79+X1gGnmYUJPw0f/UCD9U7EPYQV0GRRHwamAfKjc=,tag:Y/aXm330gR6L5Lkmmo7h0w==,type:str]
sops:
    age:
        - recipient: age1gakv6vtdd4x5z37evaq50930m89envq5xqd0m8sgwtudxx0gjalqvz7rze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUHlwbXRrbjIvSWNldThE
            RXRUYjdxODcrY2JFcUtBVGZtRkxQcHNiUHpzCmU1SDBsRzJ2bnNIcW9iZkhINTY1
            MmpXL1orR28wc1pwMVpTbTRqSmo0MEEKLS0tIEtDT2t3bno5WUZvZ3lHeDdiYVRu
            blNic2ZBZ0laYXNCNzNadDcrRVpYS1UKl4mXtlg8HR7YgFTzoeMcyq7uVOeLmZmd
            gvwHXww8v02v8FUUtpyA97GrzjqfI+RTQnkkzAKO0S25YkhV8j6o4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T09:16:54Z"
    mac: ENC[AES256_GCM,data:MK3Rq6FeAU/jDSNKjCrF0mFQ6ZL3yoUMHc80hjGR9hQWw0pcibowvzEwSZbwyQJaUUdVUh+xZdKHHSaODayKI05ShAMb30+K8KPDFS2yEKYpnDlOOsZ1gf0M5prXQFS0rctAzlPKZyPS+BCzgq4cW3T+FyWy1R3kC40vPQGj0PM=,iv:4ec+G5o7o0GJN1GeWIyhzjJs+k3Lu1YjRoiWDEVCcoI=,tag:baojWkNDl+TOghIvM9As4Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
