apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models
  namespace: models
spec:
  resources:
    requests:
      storage: 10Gi    # CHANGE this to match your intended model capacity, bigger = more models
