apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - linkding-secrets.sops.yaml
  - linkding-tls.yaml
  - ../../base/linkding

patches:
  - path: linkding-patch.yaml
    target:
      kind: HelmRelease
      name: linkding
