apiVersion: v1
kind: Secret
metadata:
    name: linkding-secrets
    namespace: linkding
type: Opaque
stringData:
    pg_username: CHANGEME        # CHANGE this to your postgres database username
    pg_password: CHANGEME        # CHANGE this to your postgres database password
