---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/proxysql
  - proxysql-admin-password.sops.yaml
  - proxysql-monitor-credentials.sops.yaml
  - proxysql-pvc.yaml

patches:
  - path: proxysql-patch.yaml
