apiVersion: apps/v1
kind: Deployment
metadata:
  name: directus
  namespace: directus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: directus
  template:
    metadata:
      labels:
        app: directus
    spec:
      containers:
        - name: directus
          image: directus/directus:11.17.1
          ports:
            - containerPort: 8055
          envFrom:
            - secretRef:
                name: directus-secrets
          volumeMounts:
            - name: uploads
              mountPath: /directus/uploads
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: directus-uploads
