apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: directus-uploads
  namespace: directus
spec:
  storageClassName: nfs-client   # CHANGE this to your storage class
  resources:
    requests:
      storage: 1Gi               # CHANGE this to how much storage you want to allocate
