# ---
# SETUP INSTRUCTIONS
# 1. Replace the placeholder values below with your actual forgejo configuration.
#    These values correspond to the [security], [server], [oauth2], [database],
#    [mailer], [storage], [lfs], etc. sections of app.ini.
# 2. Run this command to encrypt the file with your own Age key:
#    `sops --encrypt --in-place forgejo-secrets.sops.yaml`
# 3. Ensure your kustomization.yaml points to the .sops.yaml version.
# ---

apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secrets
    namespace: forgejo
type: Opaque
stringData:
    # This forms the primary config for your instance, use the pipe char
    # to set the relevant evvars for each section
    # See: https://forgejo.org/docs/latest/admin/config-cheat-sheet
    cors: |
        ENABLED=true
        ALLOW_DOMAINS=https://*.example.com,https://*.tailxxx.ts.net
    security: "YOUR_SECURITY_SECTION"
    server: "YOUR_SERVER_SECTION"
    oauth2: "YOUR_OAUTH2_SECTION"
    database: "YOUR_DATABASE_SECTION"
    queue: "YOUR_QUEUE_SECTION"
    cache: "YOUR_CACHE_SECTION"
    session: "YOUR_SESSION_SECTION"
    mailer: "YOUR_MAILER_SECTION"
    storage: "YOUR_STORAGE_SECTION"
    lfs: "YOUR_LFS_SECTION"
