apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: navidrome
  namespace: navidrome
spec:
  chart:
    spec:
      chart: navidrome
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      version: "23.4.0"
  interval: 24h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    fullnameOverride: navidrome
