apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/external-dns
  - external-dns-secrets.sops.yaml

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: external-dns
