apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - lubelogger-secret.sops.yaml
  - ../../base/lubelogger

patches:
  - path: lubelogger-patch.yaml
    target:
      kind: HelmRelease
      name: lubelogger
