apiVersion: v1
kind: Secret
metadata:
    name: lubelogger-secret
    namespace: lubelogger
type: Opaque
stringData:
    # See https://docs.lubelogger.com/Advanced/Environment%20Variables/ for all env options
    # General Config (sha256 hashes)
    ROOT_USER_HASH: root_username_hash
    ROOT_PASS_HASH: root_password_hash
    # DB Configuration
    POSTGRES_CONNECTION: Host=pg-shared-rw.databases.svc.cluster.local;Port=5432;Username=lubelogger;Password=iYUEd7ou8yiv654rsdxf0p9oubguoCD5t7fgpcd75tghG;Database=lubelogger;SslMode=Require;TrustServerCertificate=true;
    # Mail Configuration
    MailConfig__EmailServer: smtp-relay.smtp.svc.cluster.local
    MailConfig__EmailFrom: lubelogger@example.com
    MailConfig__Port: "25"
    MailConfig__Username: ""
    MailConfig__Password: ""
    # OIDC Configuration
    OpenIDConfig__Name: Authelia
    OpenIDConfig__ClientId: lubelogger
    OpenIDConfig__ClientSecret: AUTHELIA_CLIENT_SECRET
    OpenIDConfig__AuthURL: https://authelia.example.com/api/oidc/authorization
    OpenIDConfig__TokenURL: https://authelia.example.com/api/oidc/token
    OpenIDConfig__RedirectURL: https://lube.example.com/Login/RemoteAuth
    OpenIDConfig__Scope: openid profile email
    OpenIDConfig__ValidateState: "false"
    OpenIDConfig__UsePKCE: "false"
    OpenIDConfig__DisableRegularLogin: "false"
    OpenIDConfig__UserInfoURL: https://authelia.example.com/api/oidc/userinfo
    OpenIDConfig__LogOutURL: https://authelia.example.com/logout
